### PR TITLE
chore: update lumos dep

### PR DESCRIPTION
**Pull request by IronLu233**
update lumos to this branch https://github.com/ckb-js/lumos/tree/service-worker, which solves it can not request http on service worker.

### CODE REVIEW

**Comment by homura** [comment]
ci is failed, can you please fix it up

**Review by zhangyouxin — APPROVED** [review]
LGTM

**Comment by homura** [comment]
@IronLu233 can you help to resolve the conflict

**Comment by homura** [comment]
migrated to https://github.com/ckb-js/nexus/pull/105

**Pull request closed without merging**
